name: AAAI-2021
tagline: 35th AAAI Conference on Artificial Intelligence <br> A Virtual Conference
date: February 2 &ndash; 9, 2021
proceedings_title: Proceedings of the 2020 Conference on Empirical Methods in Natural Language Processing
citation_date: February 2021
analytics: UA-179777566-1
site_url: https://aaai.org/Conferences/AAAI-21/
logo:
  image: static/images/aaai2021/AAAI-logo.png
  height: 45px
site_title: AAAI-2021
page_title:
  prefix: 'AAAI2021'
  separator: ': '
background_image: static/images/aaai2021/AAAI-Banner.png
organization: AAAI-21 Conference Committee

# Path to the folder of paper images.
paper_images_path: https://emnlp2020-public.s3.amazonaws.com/paper_images

default_presentation_id: 38931484

# Remove or change to your chat server.
chat_server: 60.247.144.9:3000
channels_stats_server: https://emnlp2020-channels-stats.azure-api.net

gather_town: https://www.virtualchair.net/events/emnlp2020
connected_papers_conference_name: AAAI2021

calendar:
  start: '2020-11-16'
  end: '2020-11-20'
